# Generated by Django 3.1.7 on 2021-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='description',
            field=models.CharField(max_length=255, unique=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='document',
            field=models.FileField(upload_to='projekts/isxod_dannie', verbose_name='файл с исходными данными'),
        ),
    ]
