# Generated by Django 3.1.7 on 2021-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0003_auto_20210404_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='description',
            field=models.CharField(default='жд линия А - Б', max_length=255, verbose_name='Описание проекта'),
        ),
    ]
