# Generated by Django 3.1.7 on 2021-04-05 22:03

from django.db import migrations, models
import projektapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0008_auto_20210406_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='result_file',
            field=models.FileField(blank=True, upload_to=projektapp.models.projekt_directory_path, verbose_name='файл с результатами'),
        ),
    ]
