# Generated by Django 3.1.7 on 2021-04-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0009_auto_20210406_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='result_file',
            field=models.FileField(blank=True, upload_to='results/', verbose_name='файл с результатами'),
        ),
    ]
