# Generated by Django 3.1.7 on 2021-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0010_auto_20210406_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt',
            name='result_file',
        ),
        migrations.AddField(
            model_name='projekt',
            name='neiro_damage_flag',
            field=models.BooleanField(default=False, verbose_name='Результат выполнения расчетов сил/повреждаемостей по нейромодели'),
        ),
    ]
