# Generated by Django 3.1.7 on 2021-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0012_projekt_result_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projekt',
            old_name='result_file',
            new_name='neiro_damage_result',
        ),
    ]
