# Generated by Django 3.1.7 on 2021-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0013_auto_20210406_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='projekt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='номер проекта'),
        ),
    ]
