# Generated by Django 3.1.7 on 2021-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektapp', '0014_auto_20210406_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='process_info',
            field=models.CharField(default='ожидание действия оператора', max_length=255, verbose_name='Информация о состоянии процесса'),
        ),
    ]
