# Generated by Django 3.1.7 on 2021-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_file', models.FileField(blank=True, upload_to='isxod_dannie/', verbose_name='файл с исходными данными')),
                ('init_create', models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описением создания проекта и исходных данных')),
                ('projekt_create_activate', models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описением создания проекта и исходных данных')),
                ('projekt_neiro_calc', models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описением создания проекта и исходных данных')),
            ],
        ),
    ]
