# Generated by Django 3.1.7 on 2021-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpinfo',
            name='init_file',
            field=models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с исходными данными'),
        ),
    ]
