# Generated by Django 3.1.7 on 2021-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210406_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpinfo',
            name='init_create',
            field=models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описанием программы и процесса регистрации'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='projekt_create_activate',
            field=models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описанием создания проекта и его активации'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='projekt_neiro_calc',
            field=models.FileField(blank=True, upload_to='help_materials/', verbose_name='файл с с описанием выполнения расчета и его результатов'),
        ),
    ]
