# Generated by Django 3.1.7 on 2021-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_projektuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='projektuser',
            name='first_name',
            field=models.CharField(default='Name', max_length=10, verbose_name='Имя пользователя'),
        ),
    ]
